#názov strany
nazov_strany: AnubisSVK

#Popis webu
popis_webu: Web developer | Java Developer | Youtuber

#url webadresu
urlstranky: 

sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:title/

# Markdown rendering
markdown: kramdown